// Settings section components
export { DictationSettings } from "./dictation/DictationSettings";
export { DictionarySettings } from "./dictionary/DictionarySettings";
export { TextInsertionSettings } from "./insertion/TextInsertionSettings";
export { AppPreferences } from "./app/AppPreferences";
export { PrivacySettings } from "./privacy/PrivacySettings";
export { DebugSettings } from "./debug/DebugSettings";
export type { OnboardingPreviewStep } from "./debug/OnboardingPreview";
export { HistorySettings } from "./history/HistorySettings";
export { StatsSettings } from "./stats/StatsSettings";
export { AboutSettings } from "./about/AboutSettings";
export { CleanupSettings } from "./cleanup/CleanupSettings";
export { ModelsSettings } from "./models/ModelsSettings";

// Individual setting components
export { MicrophoneSelector } from "./MicrophoneSelector";
export { ChannelSelector } from "./ChannelSelector";
export { ClamshellMicrophoneSelector } from "./ClamshellMicrophoneSelector";
export { OutputDeviceSelector } from "./OutputDeviceSelector";
export { AlwaysOnMicrophone } from "./AlwaysOnMicrophone";
export { ShortcutActivationSetting } from "./ShortcutActivation";
export { AudioFeedback } from "./AudioFeedback";
export { ShowOverlay } from "./ShowOverlay";
export { GlobalShortcutInput } from "./GlobalShortcutInput";
export { HandyKeysShortcutInput } from "./HandyKeysShortcutInput";
export { ShortcutInput } from "./ShortcutInput";
export { TranslateToEnglish } from "./TranslateToEnglish";
export { CustomWords } from "./CustomWords";
export { PostProcessingToggle } from "./PostProcessingToggle";
export { PostProcessingSettingsApi } from "./PostProcessingSettingsApi";
export { PostProcessingSettingsPrompts } from "./PostProcessingSettingsPrompts";
export { FillerWordRemoval } from "./FillerWordRemoval";
export { AppDataDirectory } from "./AppDataDirectory";
export { ModelUnloadTimeoutSetting } from "./ModelUnloadTimeout";
export { StartHidden } from "./StartHidden";
export { HistoryLimit } from "./HistoryLimit";
export { RecordingRetentionPeriodSelector } from "./RecordingRetentionPeriod";
export { AutostartToggle } from "./AutostartToggle";
export { UpdateChecksToggle } from "./UpdateChecksToggle";
export { ShowWhatsNewOnUpdate } from "./ShowWhatsNewOnUpdate";
